print("abc","\n","bcd")
print("abc\nbcd")
print("hello\n\n!!")
print("This is '\t' means tab")
print("This","is","different",sep="\t")
print("This","is","different",sep="#")
print("This","is","different",sep=None)
print("This","is","different",sep="\n")
print("This","is","different",end=".")
