print(bool(''))
print(bool(10-10))
print(bool(19.99-19.9))
print(bool([]))
print(bool(range(0)))
print(bool(None))
print(bool(0+0.1j))
print(bool(-10))
print(bool(-9.6))
print(bool('ABC'+'KL'))
print(bool('-' ))
print(bool("False"))
print(bool(False))
print(bool("None"))